config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'registrations#new'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  delete 'delete-account/:author_id', to: 'registrations#destroy'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :authors, only: [:show, :edit, :update, :destroy] do
    resources :stories, except: [:show]
  end

  resources :stories, only: [:show] do
    resources :words, only: [:new, :create, :destroy]
  end

  get '/admin/search', to: 'authors#search'

  scope '/admin' do
    resources :authors, only: [:index]
  end

  namespace :admin do
    resources :stats, only: [:index]
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password

  has_many :words, dependent: :destroy

  has_many :stories, dependent: :destroy

  scope :most_stories, -> { left_joins(:stories).group("authors.id").order("COUNT(stories.author_id) DESC") }

  # READ: https://www.postgresql.org/docs/9.6/functions-matching.html#FUNCTIONS-POSIX-TABLE
  scope :find_author, ->(search_params) { where("first_name ~* ?", "^#{search_params[:query]}")}

  validates :first_name, :last_name, :email,
    presence: true

  validates :email,
    uniqueness: true

  validate :valid_password?

  def valid_password?
    errors.add(:password, "must be between 8 and 32 characters.") unless self.password.nil? or self.password.length.between?(8,32)
  end

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_username = auth_hash["extra"]["raw_info"]["login"]

    unless author = Author.find_by(:username => oauth_username)
      author = Author.new(:username => oauth_username, :password => SecureRandom.hex)
      author.save!(:validate => false)
    end

    return author
  end

  # replaced by scope method :most_stories
  # def self.most_stories
  #   Author
  #     .left_joins(:stories)
  #     .group("authors.id")
  #     .order("COUNT(stories.author_id) DESC")
  # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  #      Prefix      Verb         URI Pattern                   Controller#Action
  #      authors     GET          /authors(.:format)               authors#index
  #                  POST         /authors(.:format)               authors#create
  #   new_author     GET          /authors/new(.:format)           authors#new
  #  edit_author     GET          /authors/:id/edit(.:format)      authors#edit
  #       author     GET          /authors/:id(.:format)           authors#show
  #                  PATCH        /authors/:id(.:format)           authors#update
  #                  PUT          /authors/:id(.:format)           authors#update
  #                  DELETE       /authors/:id(.:format)           authors#destroy

  before_action :authenticate_author!
  before_action :redirect_if_not_admin, only: [:index, :destroy, :search]

  def index
    @authors ||= Author.all
  end

  def search
    @authors = Author.find_author(search_params)
    render :index
  end

  def show
    @author = set_author_if_admin(params[:id])
  end

  def edit
    @author = set_author_if_admin(params[:id])
  end

  def update
    @author = Author.find_by_id!(params[:id])
    params[:author][:admin] = false unless is_admin?

    if @author.update(author_params)
      redirect_to author_stories_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    Author.find_by_id!(params[:id]).destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name, :email, :admin)
  end

  def search_params
    params.permit(:query)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def display_name(author)
    "#{author.first_name} #{author.last_name}"
  end

  def possessive_display_name(author)
    name = display_name(author)
    name[-1] == "s" ? "#{name}'" : "#{name}'s"
  end
end

app/views/authors/_errors.html.erb
<% if author.errors.any? %>
  <ul class="errors">
    <% author.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/authors/edit.html.erb
<main>
  <h1>Edit<%= " #{possessive_display_name(@author) if is_admin?}" %> Profile</h1>

  <%= render partial: "errors", locals: {author: @author} %>

  <article class="edit-card">
    <%= form_for(@author, url: author_path(@author)) do |f| %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.text_field :email %>

      <% if current_author.admin %>
        <div class="label-checkbox">
          <%= f.label :admin%>
          <%= f.check_box :admin%>
        </div>
      <% end %>

      <%= f.submit "Update" %>
      <% end %>

      <% if !is_admin? %>
        <%= button_to "Cancel", author_stories_path(current_author), method: :get %>
      <% end %>
  </article>
</main>

app/views/authors/index.html.erb
<main>
  <%= button_to "Author Stats", admin_stats_path, method: :get%>
  <h1>Swahili Semantic Diary Authors</h1>

  <%= form_with(url: admin_search_path, local: true, method: "get") do %>
    <% label_tag(:query, "search for:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Search") %>
  <% end %>

  <% @authors.each do |author|%>
    <section class="author-card">
      <h2><%= link_to "#{author.first_name} #{author.last_name}", author_path(author), method: :get %></h2>
      <h3><%= "#{author.email}" %></h3>
      <button><%= link_to "Delete", author, method: :delete, data: {confirm: "Are you sure you want to delete #{display_name(author)}?"}%></button>
    </section>
  <% end %>
</main>

app/views/authors/show.html.erb
<main>
  <section class="author-card">
    <h1><%= "#{possessive_display_name(@author)} Profile" %></h1>
    <h3><%= @author.email %></h3>
    <button><%= link_to "Edit Profile", edit_author_path(@author) %></button>
  </section>

  <% if !is_admin? %>
    <%= button_to "Author's Stories", author_stories_path(current_author), method: :get %>
  <% end %>
</main>