config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'registrations#new'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  delete 'delete-account/:author_id', to: 'registrations#destroy'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :authors, only: [:show, :edit, :update, :destroy] do
    resources :stories, except: [:show]
  end

  resources :stories, only: [:show] do
    resources :words, only: [:new, :create, :destroy]
  end

  get '/admin/search', to: 'authors#search'

  scope '/admin' do
    resources :authors, only: [:index]
  end

  namespace :admin do
    resources :stats, only: [:index]
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :author

  has_many :glosses
  has_many :words, through: :glosses, dependent: :destroy
  
  validates :story_title, :story,
    presence: true

  validates :story_title,
    uniqueness: true

  validate :valid_title_length?

  validate :valid_story_length?

  def valid_title_length?
    errors.add(:story_title, "is currently #{self.story_title.length} characters long. It must be between 3 and 60 characters") unless self.story_title.nil? or self.story_title.length.between?(3,60)
  end

  def valid_story_length?
    errors.add(:story, "is currently #{self.story_word_length} words long. It must be between 5 and 500 words.") unless self.story.nil? or self.story_word_length.between?(5,500)
  end

  def story_word_length
    self.story.split(" ").length
  end

  def word_glosses
    self.words.uniq.map do |w|
      {
        :word => w,
        :glosses => w.glosses.collect{|g| g.gloss}.join("; ")
      }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_author!

  def index
    @author = current_author
  end

  def new
    @story = current_author.stories.build
  end

  def create
    @story = current_author.stories.build(story_params)
    if @story.save
      redirect_to new_story_word_path(@story)
    else
      render :new
    end
  end

  def show
    @story = Story.find_by_id!(params[:id])
  end

  def edit
    @story = Story.find_by_id!(params[:id])
  end

  def update
    @story = Story.find_by_id!(params[:id])

    if @story.update(story_params)
      flash[:alert] ="Your story was updated!"
      redirect_to author_stories_path(@story)
    else
      render :edit
    end
  end

  def destroy
    Story.find_by_id!(params[:id]).destroy
    redirect_to author_stories_path
  end

  private
  def story_params
    params.require(:story).permit(:story_title, :story)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_new.html.erb
<article class="new-story-card">
  <h1>Write a New Swahili Diary Entry</h1>
  <%= form_for(@story), url: new_author_story(@story) do |f| %>
    <div class="story-fields">
      <%= f.label :story_title %>
      <%= f.text_field :story_title %>

      <%= f.label :story %>
      <%= f.text_area_tag(:story, "write your story here...") %>

      <%= f.submit "Publish Story" %>
    </div>
  <% end %>
</article>

app/views/stories/_new_edit_form.html.erb
<%= form_with model: [current_author, story], local: true, class: "new-story-form" do |f| %>
  <%= f.text_field :story_title, :placeholder => "Story's title", :autofocus => true  %>
  <%= f.text_area :story, :placeholder => "Swahili story" %>
  <%= f.submit "Publish" %>
  <% if !story.id.nil? %>
    <%= link_to "Cancel", new_story_word_path(story) %>
  <% end %>
<% end %>

app/views/stories/_new_edit_layout.html.erb
<% if @story.errors.any? %>
  <ul class="errors">
    <% @story.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= yield %>

<% if story.id.nil? %>
  <%= link_to "Cancel", author_stories_path(current_author), method: :get %>
<% end %>

app/views/stories/edit.html.erb
<main>
  <h1>Edit Your Swahili Diary Entry</h1>
  <article class="edit-story-card">
    <%= render partial: "new_edit_form", locals: {story: @story}, layout: "new_edit_layout" %>
  </article>
</main>

app/views/stories/index.html.erb
<main>
  <% if flash[:alert] %>
    <ul class="flash-alert">
      <li><%= flash[:alert] %></li>
    </ul>
  <% end %>

  <h1><%= link_to "#{@author.first_name}'s", edit_author_path(@author) %> Swahili Diary</h1>
  <% # render 'new' %>

  <h3><%= link_to "Write New Story",  new_author_story_path %></h3>
    <% @author.stories.reverse.each do |story| %>
      <article class="story-card">
        <h3><%= link_to story.story_title, new_story_word_path(story), method: :get %></h3>
        <p><%= story.story %></p>
        <button><%= link_to "Delete Story", author_story_path(current_author,story), method: :delete %></button>
      </article>
    <% end %>
</main>

app/views/stories/new.html.erb
<main>
  <h1>Write a New Swahili Diary Entry</h1>
  <article class="new-story-card">
    <%= render partial: "new_edit_form", locals: {story: @story}, layout: "new_edit_layout" %>
  </article>
</main>

app/views/stories/show.html.erb
<main>
  <%= button_to("Your Stories", author_stories_path(current_author), method: :get) if !is_admin? %>

  <article class="story-card">
    <h1><%= @story.story_title %></h1>
    <p><%= @story.story %></p>
    <%= button_to("Edit", edit_author_story_path(@story), method: :get) if !is_admin? %>
  </article>

</main>