config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'registrations#new'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  delete 'delete-account/:author_id', to: 'registrations#destroy'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :authors, only: [:show, :edit, :update, :destroy] do
    resources :stories, except: [:show]
  end

  resources :stories, only: [:show] do
    resources :words, only: [:new, :create, :destroy]
  end

  get '/admin/search', to: 'authors#search'

  scope '/admin' do
    resources :authors, only: [:index]
  end

  namespace :admin do
    resources :stats, only: [:index]
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :author

  has_many :glosses
  has_many :stories, through: :glosses, dependent: :destroy

  # accepts_nested_attributes_for :glosses

  validates :lemma,
    presence: true


  def glosses_attributes=(glosses_attributes)
    glosses_attributes.each do |gloss_attribute|
      word_id = self.id
      gloss = gloss_attribute[1][:gloss]
      story_id = gloss_attribute[1][:story_id]

      gloss = Gloss.find_or_create_by(:gloss => gloss, :story_id => story_id, :word_id => word_id)
      self.glosses << gloss
    end
  end

  def self.find_or_create_lemma(word_params)
    Word.find_or_create_by(:lemma => word_params[:lemma],
                           :lexical_category => word_params[:lexical_category],
                           :lemma_class => word_params[:lemma_class],
                           :author_id => word_params[:author_id]
                          )
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new
    @word = Word.new
  end

  def create
    if (@word = Word.find_or_create_lemma(word_params)) && @word.update(word_params)
      redirect_to new_story_word_path(current_story)
    else
      render :new
    end
  end

  def destroy
    Word.find_by_id!(params[:id]).destroy
    redirect_to new_story_word_path(current_story)
  end

  private
    def word_params
      params.require(:word).permit(:lemma, :lexical_category, :lemma_class, :notes, :origin, :author_id, glosses_attributes: [:gloss, :story_id])
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/new.html.erb
<main>
  <%= button_to("Your Stories", author_stories_path(current_author), method: :get) if !is_admin? %>

  <article class="story-card">
    <h1><%= current_story.story_title %></h1>
    <p><%= current_story.story %></p>
    <%= button_to("Edit", edit_author_story_path(current_author, current_story), method: :get) if !is_admin? %>
  </article>

  <article class="new-word-card">
    <h2>Glossary</h2>
    <% # form_with model: [@word, @gloss], local: true, cache: false do |f| %>
    <%= form_for(@word, url: story_words_path(current_story, @word)) do |f| %>
      <section class="new_word--input">
        <div>
          <%= f.label :lemma %>
          <%= f.text_field :lemma, :placeholder => "Swahili base word", :autofocus => true %>
        </div>
        <div>
          <%= f.fields_for :glosses, @word.glosses.build do |g| %>
            <%= g.label :gloss %>
            <%= g.text_field :gloss, :placeholder => "Gloss for this word" %>
            <%= g.hidden_field :story_id, :value => current_story.id %>
          <% end %>
        </div>
        <div>
          <%= f.label :notes %>
          <%= f.text_field :notes, :placeholder => "Plural, irregularity, etc." %>
        </div>
      </section>
      <section class="new_word--input">
        <div> 
          <%= f.label :lexical_category %>
          <%= f.select :lexical_category, ["noun", "pron", "verb", "adj", "adv", "prep", "conj", "det", "intj",""] %>
        </div>
        <div>
          <%= f.label :lemma_class %>
          <%= f.select :lemma_class, ["trans", "intrs", "m-/wa-", "m-/mi-", "ji-/ma-", "ki-/vi", "n-/n-", "u-/u-", "ku-", "pa-", ""] %>
        </div>
        <div>
          <%= f.label :origin %>
          <%= f.select :origin, ["Bantu", "Arabic", "Persian", "Hindi", "English", ""] %>
          <%= f.hidden_field :author_id, :value => current_author.id %>
        </div>
      </section>
      <%= f.submit "Add Word" %>
    <% end %>

    <% if !current_story.word_glosses.empty?  %>
      <article class="glossary-card">
        <% current_story.word_glosses.each do |word_gloss| %>
          <% w = word_gloss[:word] %>
          <% glosses = word_gloss[:glosses] %>

          <section class="lemma-card newspaper">
            <span class="lemma-card--delete"><%= link_to "x", story_word_path(current_story,w), method: :delete %></span>
            <span class="lemma-card--lemma"><%= w.lemma %></span>
            <span class="lemma-card--lexical-category"><%= w.lexical_category %></span>
            <span class="lemma-card--lemma-class"><%= w.lemma_class %></span>
            <span class="lemma-card--notes"><%= w.notes %></span>
            <span class="lemma-card--origin"><%= w.origin %></span>
            <p class="lemma-card--glosses"><%= glosses %></p>
          </section>
        <% end %>
      </article>
    <% end %>
  </article>

</main>