config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'registrations#new'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  delete 'delete-account/:author_id', to: 'registrations#destroy'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :authors, only: [:show, :edit, :update, :destroy] do
    resources :stories, except: [:show]
  end

  resources :stories, only: [:show] do
    resources :words, only: [:new, :create, :destroy]
  end

  get '/admin/search', to: 'authors#search'

  scope '/admin' do
    resources :authors, only: [:index]
  end

  namespace :admin do
    resources :stats, only: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SwahiliSemanticDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if current_author %>
        <%= link_to "Log out #{display_name(current_author)}", logout_path, method: :get %>
      <% else %>
        <span>
          <%= link_to "Sign up", sign_up_path, method: :get %> |
          <%= link_to "Log in", login_path, method: :get %>
        </span>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>